default_stages: [commit]
default_language_version:
  python: python3
repos:
  - repo: micode@micode.be.xiaomi.com:hook/pre-commit-common.git
    rev: master
    hooks:
      - id: check-bom
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: ["--branch=RELEASE","--branch=master"]
      - id: check-message
        stages: [commit-msg]
      - id: collect-user
      - id: check-branch
  - repo: micode@micode.be.xiaomi.com:hook/pre-commit-php.git
    rev: master
    hooks:
      - id: phpcs-fixer
      - id: php-lint
